name: Windows CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Running on Windows

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install OpenSSH Client for SSH deployment (if needed)
      - name: Install OpenSSH Client
        run: |
          Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
        shell: powershell

      # 3. Deploy to Server via SSH using PowerShell
      - name: Deploy to Server
        run: |
          $privateKey = "${{ secrets.SSH_PRIVATE_KEY }}"
          $keyFile = "$env:USERPROFILE\\.ssh\\id_rsa"
          $privateKey | Out-File -FilePath $keyFile -Force
          chmod 600 $keyFile  # Set appropriate permissions
          
          ssh -i $keyFile -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd ${{ secrets.REMOTE_PATH }} &&
            git pull origin main
          "
        shell: powershell
