name: Build, Push and Save Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image:latest .

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest

    - name: List Docker Images
      run: docker images

    - name: Save Docker Image to File
      run: |
        docker save ${{ secrets.DOCKER_USERNAME }}/my-image:latest -o image.tar
        mkdir -p D:/docker-images
        mv image.tar D:/docker-images
